[package]
name = "macrojazz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
ariadne = "0.1.5"
codemap = "0.1.3"
codemap-diagnostic = "0.1.1"
peg = "0.8.0"
