# CI triggered on commit
matrix:
  platform:
    - linux/amd64
    - linux/arm64 

platform: ${platform}

pipeline:
  build:
    image: debian:stable-slim
    commands:
      # Install rustup
      - curl https://sh.rustup.rs -sSf | sh
      # Install stable rust toolchain
      - rustup install stable
      # Build crate
      - cargo build --release
